name: Gerar PDF e Atualizar README

on:
  push:
    paths:
      - 'dados_curriculo.json'
      - 'gerar_pdf.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: pip install fpdf

      - name: Gerar PDF
        run: python gerar_pdf.py

      - name: Commit e Push dos arquivos gerados
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add curriculo_fabiano.pdf
          git commit -m "Automação: PDF atualizado" || exit 0
          git push
