name: Gerar Curriculo

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Instalar FPDF
        run: pip install fpdf
      - name: Gerar PDF
        run: python gerar_pdf.py
      - name: Salvar Arquivo
        uses: actions/upload-artifact@v4
        with:
          name: curriculo-final
          path: curriculo_fabiano.pdf